[tool.poetry]
name = "saketrail-infra"
version = "0.1.0"
description = "Infrastructure as Code for SakeTrail"
authors = ["Your Name <your.email@example.com>"]

packages = [
    { include = "saketrail_cdk" }
]

[tool.poetry.dependencies]
python = "^3.11"
aws-cdk-lib = "^2.0.0"
constructs = "^10.0.0"
pyyaml = "^6.0.2"
boto3 = "^1.34.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
black = "^24.0.0"
isort = "^5.0.0"
flake8 = "^7.0.0"
moto = "^5.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 