domain: dev.saketrail.vdnih.link
certificate_arn: arn:aws:acm:us-east-1:597088033984:certificate/02bed00a-8836-4573-b591-110c779ee347
s3:
  frontend_bucket:
    name: dev-saketrail-frontend
    error_document: index.html
    index_document: index.html

cloudfront:
  price_class: PRICE_CLASS_200  # 北米、欧州、アジア、オセアニア
  minimum_protocol_version: TLSv1.2_2021 