name: Flutter Web Build and Deploy to S3

on:
  push:
    branches:
      - main  # mainブランチへのpushでトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Create .env file
      run: |
        echo "MICROCMS_SERVICE_NAME=${{ secrets.MICROCMS_SERVICE_NAME }}" >> .env
        echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> .env

    - name: Build Flutter Web
      run: flutter build web --release

    - name: Set up AWS OIDC credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::597088033984:role/github-oicd-role-for-sakeflow  # 作成したIAMロールのARN
        role-session-name: GitHubActions
        aws-region: 'ap-northeast-1'  # 使用しているAWSリージョン

    - name: Deploy to S3
      run: |
        aws s3 sync ./build/web/ s3://sakeflow --delete
